// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qtWvXH8Uhh67sc1TY2MZeK
// Component: zd0kYk846W4g

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { AntdMenuDivider } from "@plasmicpkgs/antd5/skinny/registerMenu";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_pro_pro.module.css"; // plasmic-import: qtWvXH8Uhh67sc1TY2MZeK/projectcss
import sty from "./PlasmicErrorMessageContainer.module.css"; // plasmic-import: zd0kYk846W4g/css

createPlasmicElementProxy;

export type PlasmicErrorMessageContainer__VariantMembers = {};
export type PlasmicErrorMessageContainer__VariantsArgs = {};
type VariantPropType = keyof PlasmicErrorMessageContainer__VariantsArgs;
export const PlasmicErrorMessageContainer__VariantProps =
  new Array<VariantPropType>();

export type PlasmicErrorMessageContainer__ArgsType = {};
type ArgPropType = keyof PlasmicErrorMessageContainer__ArgsType;
export const PlasmicErrorMessageContainer__ArgProps = new Array<ArgPropType>();

export type PlasmicErrorMessageContainer__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  menuDivider?: p.Flex<typeof AntdMenuDivider>;
};

export interface DefaultErrorMessageContainerProps {
  className?: string;
}

const $$ = {};

function PlasmicErrorMessageContainer__RenderFunc(props: {
  variants: PlasmicErrorMessageContainer__VariantsArgs;
  args: PlasmicErrorMessageContainer__ArgsType;
  overrides: PlasmicErrorMessageContainer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1YolR
          )}
        >
          {"Title Text"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ez3Ma
          )}
        >
          {"message"}
        </div>
        <AntdMenuDivider
          data-plasmic-name={"menuDivider"}
          data-plasmic-override={overrides.menuDivider}
          className={classNames("__wab_instance", sty.menuDivider)}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "menuDivider"],
  freeBox: ["freeBox", "menuDivider"],
  menuDivider: ["menuDivider"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  menuDivider: typeof AntdMenuDivider;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicErrorMessageContainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicErrorMessageContainer__VariantsArgs;
    args?: PlasmicErrorMessageContainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicErrorMessageContainer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicErrorMessageContainer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicErrorMessageContainer__ArgProps,
          internalVariantPropNames: PlasmicErrorMessageContainer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicErrorMessageContainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicErrorMessageContainer";
  } else {
    func.displayName = `PlasmicErrorMessageContainer.${nodeName}`;
  }
  return func;
}

export const PlasmicErrorMessageContainer = Object.assign(
  // Top-level PlasmicErrorMessageContainer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    menuDivider: makeNodeComponent("menuDivider"),

    // Metadata about props expected for PlasmicErrorMessageContainer
    internalVariantProps: PlasmicErrorMessageContainer__VariantProps,
    internalArgProps: PlasmicErrorMessageContainer__ArgProps
  }
);

export default PlasmicErrorMessageContainer;
/* prettier-ignore-end */
